version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ffmpeg:
    image: jrottenberg/ffmpeg
    volumes:
      - ./media:/media
    command: ["-version"]  # Keep container running

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: videomaker_dev
      POSTGRES_USER: postgres_video_user
      POSTGRES_PASSWORD: postgres_usr_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # web:
  #     build: .
  #     command: python manage.py runserver 0.0.0.0:8000
  #     volumes:
  #       - .:/app
  #     ports:
  #       - "8000:8000"
  #     env_file:
  #       - .env
  #     depends_on:
  #       - postgres


volumes:
  redis_data:
  postgres_data:
